// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"first.fm/internal/persistence/shared"
)

type User struct {
	UserID         shared.ID
	LastfmUsername string
	CreatedAt      time.Time
}
