// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type LastfmUser struct {
	GuildID   string `json:"guild_id"`
	DiscordID string `json:"discord_id"`
	Username  string `json:"username"`
}
